question_data = [{"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
                  "question": "Rick, Carl, Daryl, Morgan, "
                              "Carol and Maggie were introduced to us in Season 1.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "The Neanderthals were a direct ancestor of modern humans.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "Amazon acquired Twitch in August 2014 for $970 million dollars.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "Soulja Boys Crank That; won a Grammy for Best Rap Song in 2007.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "The cover of The Beatles album Abbey Road; featured a Volkswagen Beetle in the background.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "The first televised presidential debate was between Jimmy Carter and Gerald Ford.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "Scottish producer Calvin Harris is from the town of Dumfries, Scotland.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "medium",
                  "question": "In the game Rack; you may pick up ANY card from the discard pile.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Israel is 7 hours ahead of New York.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                  "question": "The Japanese Shinkansen beat the French TGVs speed record for fastest electric rail train.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "Assyrian king Sennacherib&#039;s destruction of Babylon in 689 BCE was viewed as a triumph by other Assyrian citizens.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "&quot;I disapprove of what you say, but I will defend to the death your right to say it&quot; is a quote from French philosopher Voltaire.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "Shrimp can swim backwards.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The sum of all the numbers on a roulette wheel is 666.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                  "question": "The colour of the pills in the Matrix were Blue and Yellow.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "The Ace Attorney trilogy was suppose to end with &quot;Phoenix Wright: Ace Attorney &minus; Trials and Tribulations&quot; as its final game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "Type 1 diabetes is a result of the liver working improperly.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "Ashley Frangipane performs under the stage name Halsey.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "Tony Hawk&#039;s Pro Skater was released in 1999.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "You are allowed to sell your soul on eBay.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The average woman is 5 inches \/ 13 centimeters shorter than the average man.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Mythology", "type": "boolean", "difficulty": "medium",
                  "question": "According to Norse mythology, Loki is a mother.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "Scientists accidentally killed the once known world&#039;s oldest living creature, a mollusc, known to be aged as 507 years old.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "In Half-Life 2, if you play the zombies&#039; speech in reverse, they actually speak coherent English.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Kissing someone for one minute burns about 2 calories.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
                  "question": "The television show Doctor Who first aired in 1963.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "The Sniper&#039;s SMG in Team Fortress 2, was originally intended to be the Scout&#039;s primary weapon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "medium",
                  "question": "The average lifespan of a wildcat is only around 5-6 years. ", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "medium",
                  "question": "In the webcomic Homestuck, the first character introduced is Dave Strider.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "United States President Ronald Reagan was the first president to appoint a woman to the Supreme Court. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "medium",
                  "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                  "question": "Bugatti was an Italian car manufacturer.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                  "question": "Joan Cusack starred in the 2009 disaster movie, &quot;2012&quot;.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
                  "question": "Nickelodeon rejected the pilot to Adventure Time.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
                  "question": "Zero factorial is equal to zero. ", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "Android versions are named in alphabetical order.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "Sugar contains fat.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "medium",
                  "question": "Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
                  "question": "The set of all algebraic numbers is countable.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "&quot;Santa Claus&quot; is a variety of melon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                  "question": "In &quot;Call Of Duty: World At War&quot;, the first appearance of the &quot;PPSH-41&quot; in &quot;Zombies&quot; was in the map &quot;Der Riese&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
                  "question": "You can square root a negative number with an imaginary number &quot;i&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "The title of the 1969 film &quot;Krakatoa, East_of Java&quot; is incorrect, as Krakatoa is in fact west of Java.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                  "question": "The most frequent subconscious activity repeated by the human body is blinking.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "medium",
                  "question": "Jeb Bush was elected as Governor of Florida in 2002, starting his political career.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "medium",
                  "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
                  "question": "In Full Metal Panic!, Whispered are those who are capable of creating Black Technology.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
